name: MMO
author: MMO
baseurl: 
description: 灵魂前端打字员
github: http://github.com/yzk114360
bannerText: 123
# QQ: 11436052
# facebook: http://www.facebook.com
# linkedin: http://www.linkedin.com
# email: rnpatel[at]me.com
# location: 42°2'16"N   70°12'47"W
# disqus: diqus-username

##Make sure to edit the above fields, especially for disqus.


highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
